CREATE TABLE bookshelf (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cover_url TEXT NOT NULL,
    title TEXT NOT NULL,
    author TEXT,
    description TEXT,
    average_rating SMALLINT,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);
